<?php

/**
 *  * Implements hook_views_api().
 *   */
function himoldex_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Fix in date/pathauto module
 */
function himoldex_pathauto_alias_alter(&$alias, array &$context) {
  if ($context['module'] == 'node' && $context['type'] == 'video') {
    // Remove the buggy date token.
    $alias = str_replace('-000000', '', $alias);
  }
}

/**
 * Implements hook_node_prepare().
 *
 * - Add new videos from YouTube playlist.
 */
function himoldex_node_prepare($node) {
  if (!empty($node->nid) && ($node->type == 'course')) {
    $node_wrapper = entity_metadata_wrapper('node', $node);
    $youtube_playlist = $node_wrapper->field_youtube_playlist->value();
    if ($youtube_playlist) {
      $videos_added = 0;
      // Use caching to get last used page token.
      $pagetoken_cache_id = 'himoldex:youtube_playlist_pagetoken:' . $node->nid;
      $pagetoken_cache = cache_get($pagetoken_cache_id, 'cache_himoldex');
      if (!$pagetoken_cache) {
        $pageToken = '';
      }
      else {
	$pageToken = $pagetoken_cache->data;
      }
      // Setup YouTube/Google API
      $glib_info = libraries_info('google-api-php-client');
      $glib_path = libraries_get_path('google-api-php-client');
      set_include_path(get_include_path() . PATH_SEPARATOR . DRUPAL_ROOT . '/' . $glib_path . '/' . $glib_info['path']);
      libraries_load('google-api-php-client');
      require_once 'Google/Service/YouTube.php';
      $client = new Google_Client();
      $client->setApplicationName("HiMoldeX");
      // FIXME: Move API key to settings.
      $client->setDeveloperKey('AIzaSyAaxdSVmR7z4svlhm0V1nL1a0azqQ0gG8E');
      $service = new Google_Service_YouTube($client);
      // Fetch only 10 items on each display of the node edit page
      $itemsPerRequest = 10;
      $optParams = array('playlistId' => $youtube_playlist, 'pageToken' => $pageToken, 'maxResults' => $itemsPerRequest);
      $results = $service->playlistItems->listPlaylistItems('snippet', $optParams);
      // Warn if there are more videos to fetch (and cache the next page token to use).
      if (isset($results['nextPageToken'])) {
	cache_set($pagetoken_cache_id, $results['nextPageToken'], 'cache_himoldex');
	$message = sprintf('Hentet %s videoer fra spillelisten, men det er flere - <a href="%s">last siden på nytt</a>. (pageToken: %s)',
          $itemsPerRequest, request_uri(), $pageToken);
        drupal_set_message($message, 'warning');
      }
      // Loop over videos in playlist and check if they exists on HiMoldeX.
      foreach($results['items'] as $item) {
        $video_title = $item['snippet']['title'];
        // Skip promo videos.
        if (stripos($video_title, ' Promo') !== FALSE) {
          continue;
        } 
        $video_id = $item['snippet']['resourceId']['videoId'];
        $query = new EntityFieldQuery();
        $query->entityCondition('entity_type', 'node')
          ->entityCondition('bundle', 'video')
          ->fieldCondition('field_video_youtube', 'video_id', $video_id, '=');
        $result = $query->execute();
        if (!isset($result['node'])) {
          $videos_added++;
          $youtube_videolink = "https://www.youtube.com/watch?v=" . $video_id;
          $video_published = $item['snippet']['publishedAt'];
          list ($video_date, $dummy) = explode('T', $video_published);

          $node = new stdClass();
          $node->type = 'video';
          node_object_prepare($node);

          $node->language = 'nb';
          $node->field_video_type[LANGUAGE_NONE][0]['value'] = 'lecture';
          $node->field_video_topic[LANGUAGE_NONE][0]['value'] = $video_title;
          $node->field_video_youtube[LANGUAGE_NONE][0]['input'] = $youtube_videolink;
          $node->field_video_youtube[LANGUAGE_NONE][0]['video_id'] = $video_id;
          $node->field_video_dato[LANGUAGE_NONE][0] = array(
            'value' =>  "$video_date 00:00:00",
            'timezone' => 'Europe/Oslo',
            'timezone_db' =>   'Europe/Oslo',
            'date_type' => 'datetime',
          );

          node_save($node);
          drupal_set_message("Opprettet video '$video_title' automatisk fra spillelisten på YouTube.");
        }
      }
      if ($videos_added == 0) {
        drupal_set_message("Ingen nye videoer funnet i spillelisten på YouTube.");
      }
   }
  }
}

/**
 * Implements hook_node_validate().
 *
 * - Avoid duplicate course codes.
 */
function himoldex_node_validate($node, $form) {
  // Only validate courses.
  $course_type = 'course';
  if ($node->type == $course_type) {
    $node_wrapper = entity_metadata_wrapper('node', $node);
    $course_code = $node_wrapper->field_course_code->value();
    // Don't validate existing nodes with unchanged course code.
    if (!empty($node->nid)) {
      $orig_node = node_load($node->nid);
      $orig_node_wrapper = entity_metadata_wrapper('node', $orig_node);
      $orig_course_code = $orig_node_wrapper->field_course_code->value();
      if ($course_code == $orig_course_code) {
	return;
      }
    }
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', $course_type)
      ->fieldCondition('field_course_code', 'value', $course_code, '=');
    $result = $query->execute();
    if (isset($result['node'])) {
      form_set_error('field_course_code', t('Det fins allerede et emne med denne koden.'));
    }
  }
}


/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Making it clear that we use our full names for user registration.
 */
function himoldex_form_user_login_alter(&$form, &$form_state, $form_id) {
  $form['name']['#description'] = 'Ditt vanlige brukernavn ved Høgskolen i Molde.';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Room and phone shouldn't be editable.
 */
function himoldex_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  $form['field_room']['#disabled'] = TRUE;
  $form['field_phone']['#disabled'] = TRUE;
}

/**
 * Implements hook_block_info().
 */
function himoldex_block_info() {
  $blocks['studyhandbook_and_samordnaopptak'] = array(
    'info' => t('HimoldeX: Lenke til studiehåndbok og Samordna opptak'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['studyhandbook_and_subjects'] = array(
    'info' => t('HimoldeX: Lenke til studiehåndbok og informasjon om emnestudent'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['studyhandbook'] = array(
    'info' => t('HimoldeX: Lenke til studiehåndbok'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['about_social'] = array(
    'info' => t('HimoldeX: Lenker til Om-siden og sosiale tjenester'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['promo_video_tour'] = array(
    'info' => t('HimoldeX: Promovideo Tour (YouTube)'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['promo_video_pres'] = array(
    'info' => t('HimoldeX: Promovideo Pres. (YouTube)'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['latest_lecture'] = array(
    'info' => t('HimoldeX: Siste forelesning (YouTube)'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['banner_small'] = array(
    'info' => t('HimoldeX: Banner liten'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['banner'] = array(
    'info' => t('HimoldeX: Banner'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['study_big_logo'] = array(
    'info' => t('HimoldeX: Stor logo for studium'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['study_small_logo_logistikk'] = array(
    'info' => 'HimoldeX: Liten logo for logistikk',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['study_small_logo_okonomi'] = array(
    'info' => 'HimoldeX: Liten logo for økonomi',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['study_small_logo_samfunn'] = array(
    'info' => 'HimoldeX: Liten logo for juss og samfunnsfag',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['study_small_logo_idrett'] = array(
    'info' => 'HimoldeX: Liten logo for idrett',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['study_small_logo_sykepleie'] = array(
    'info' => 'HimoldeX: Liten logo for sykepleie',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['study_small_logo_vernepleie'] = array(
    'info' => 'HimoldeX: Liten logo for vernepleie',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['study_small_logo_it'] = array(
    'info' => 'HimoldeX: Liten logo for IT',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['study_small_logo_euv'] = array(
    'info' => 'HimoldeX: Liten logo for EUV',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['study_small_logo_ALL'] = array(
    'info' => 'HimoldeX: Liten logo for alle emner',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function himoldex_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.
  $block['subject'] = '<none>';
  switch ($delta) {
    case 'studyhandbook_and_samordnaopptak':
    case 'studyhandbook_and_subjects':
    case 'studyhandbook':
    case 'about_social':
    case 'promo_video_tour':
    case 'promo_video_pres':
    case 'latest_lecture':
    case 'banner':
    case 'banner_small':
    case 'study_big_logo':
      $block['content'] = _himoldex_block_contents($delta);
      break;
    case 'study_small_logo_logistikk':
      $block['content'] = _himoldex_block_contents($delta, 'Logistikk');
      break;
    case 'study_small_logo_okonomi':
      $block['content'] = _himoldex_block_contents($delta, 'Økonomi');
      break;
    case 'study_small_logo_samfunn':
      $block['content'] = _himoldex_block_contents($delta, 'Juss og samfunnsfag');
      break;
    case 'study_small_logo_idrett':
      $block['content'] = _himoldex_block_contents($delta, 'Idrett');
      break;
    case 'study_small_logo_sykepleie':
      $block['content'] = _himoldex_block_contents($delta, 'Sykepleie');
      break;
    case 'study_small_logo_vernepleie':
      $block['content'] = _himoldex_block_contents($delta, 'Vernepleie');
      break;
    case 'study_small_logo_it':
      $block['content'] = _himoldex_block_contents($delta, 'IT');
      break;
    case 'study_small_logo_euv':
      $block['content'] = _himoldex_block_contents($delta, 'Videre- og etterutdanning');
      break;
    case 'study_small_logo_ALL':
      $block['content'] = _himoldex_block_contents($delta, 'Alle emner');
      break;
  }
  return $block;
}

/**
 * Produces the actual block content.
 */
function _himoldex_block_contents($which_block, $title='') {
    switch ($which_block) {
    case 'studyhandbook_and_samordnaopptak':
      $html = <<<EOM
<p>
    Les i <a href="http://himolde.studiehandbok.no/">studiehåndboken</a> for mer informasjon 
    om våre studier og gå til <a href="http://www.samordnaopptak.no/">Samordna opptak</a> for å søke. 
    Søknadsfrist 15. april.
</p>
EOM;
      return array('#markup' => $html);
    case 'studyhandbook_and_subjects':
      $html = <<<EOM
<ul>
<li>Les i <a href="http://himolde.studiehandbok.no/">studiehåndboken</a> for mer informasjon om våre studier.</li>
<li>Du kan søke om å bli <a href="http://www.himolde.no/studier/Sider/Opptak/Opptak-til-enkeltemne.aspx">emnestudent</a> innen 15. august.</li>
</ul>
EOM;
      return array('#markup' => $html);
    case 'studyhandbook':
      $html = <<<EOM
<p>
    Les i <a href="http://himolde.studiehandbok.no/">studiehåndboken</a> for mer informasjon 
    om våre studier.
</p>
EOM;
      return array('#markup' => $html);
    case 'about_social':
      $html = <<<EOM
<div id="about-social" class="clearfix">
<div class="grid-5">
<!-- a href="/side/om-himoldex">Om HiMoldeX</a -->
Generelt: <a href="mailto:studentservice@himolde.no">studentservice@himolde.no</a> / 712&nbsp;14&nbsp;000
</div>
<div class="grid-2 no-margin center">Følg oss på 
<span class="no-br">
<a href="http://www.facebook.com/himolde" target="_blank"><img src="/img/fb.png"></a>
<a href="http://twitter.com/himolde" target="_blank"><img src="/img/twitter.png"></a>
<a href="http://www.youtube.com/user/himoldex" target="_blank"><img src="/img/youtube.png"></a>
</span>
</div>
<div class="grid-5 last">
Teknisk: <a href="mailto:support@himolde.no">support@himolde.no</a> / 712&nbsp;14&nbsp;175
</div>
</div>
EOM;
      return array('#markup' => $html);
    case 'about_social_old':
      $html = <<<EOM
<p id="about-social">
<a href="/side/om-himoldex">Om HiMoldeX</a> | Følg oss på 
<a href="http://www.facebook.com/himolde" target="_blank"><img src="/img/fb.png" /></a> 
<a href="http://twitter.com/himolde" target="_blank"><img src="/img/twitter.png" /></a> 
<a href="http://www.youtube.com/user/himoldex" target="_blank"><img src="/img/youtube.png" /></a> | 
Kontakt oss på <a href="mailto:post@himoldex.no" target="_blank">post@himoldex.no</a> | Vår offisielle hjemmeside:
<a href="http://www.himolde.no" target="_blank">www.himolde.no</a> 
</p>
EOM;
      return array('#markup' => $html);
    case 'promo_video_tour':
      // ID of promo video
      $youtube_video_id = 'ue_UTxmtx5Y';
      $html = <<<EOM
<div class="yt_container_third"><div id="yt_player"><img src="/sites/default/files/promovideo-stillbilde-640px.jpg" /></div></div>
EOM;
      if (!user_is_logged_in()) {
	$html .= _himoldex_youtube_js($youtube_video_id);
      }
      return array('#markup' => $html);
    case 'promo_video_pres':
      // ID of promo video
      $youtube_video_id = 'gqTqAv-Ee_U';
      $html = <<<EOM
<div class="yt_container_third"><div id="yt_player"><img src="/sites/default/files/promovideo-stillbilde-640px.jpg" /></div></div>
EOM;
      if (!user_is_logged_in()) {
	$html .= _himoldex_youtube_js($youtube_video_id);
      }
      return array('#markup' => $html);
    case 'latest_lecture':
      // Get the ID of the latest Youtube video. (We are skipping Mediasite videos for now.)
      $query = new EntityFieldQuery();
      $query->entityCondition('entity_type', 'node')
	->entityCondition('bundle', 'video')
	->fieldCondition('field_video_type', 'value', 'lecture', '=')
	->fieldCondition('field_video_youtube', 'video_id', 'NULL', '!=')
	->propertyOrderBy('created', 'DESC')
	->range(0,1);
      $result = $query->execute();
      $fields = field_info_instances('node', 'video');
      $field_id = $fields['field_video_youtube']['field_id'];
      $videos = $result['node'];
      field_attach_load('node', $videos, FIELD_LOAD_CURRENT, array('field_id' => $field_id));
      $field_video_youtube = field_get_items('node', reset($videos), 'field_video_youtube');
      $youtube_video_id = $field_video_youtube[0]['video_id'];
      // Produce the HTML
      $html = <<<EOM
<!-- iframe src="//www.youtube.com/embed/ue_UTxmtx5Y?rel=0&amp;autoplay=1" frameborder="0" width="352" height="198"></iframe -->
<div class="yt_container_third"><div id="yt_player"><img src="/sites/default/files/promovideo-stillbilde-640px.jpg" /></div></div>
EOM;
      if (!user_is_logged_in()) {
	$html .= _himoldex_youtube_js($youtube_video_id);
      }
      return array('#markup' => $html);
    case 'banner_small':
      $html = <<<EOM
<p>
<a href="/"><img src="/img/banner-liten-2013-03-11.jpg" width="100%" 
title="HiMoldeX.no er en åpen kursplattform ved Høgskolen i Molde. 
På denne siden finner du kursmateriell for utvalgte kurs ved HiMolde."/></a>
</p>
EOM;
      return array('#markup' => $html);
    case 'banner':
      $html = <<<EOM
<p>
<a href="/"><img src="/img/banner-2013-03-11.jpg" width="100%" 
title="HiMoldeX.no er en åpen kursplattform ved Høgskolen i Molde. 
På denne siden finner du kursmateriell for utvalgte kurs ved HiMolde."/></a>
</p>
EOM;
      return array('#markup' => $html);
    case 'study_big_logo':
      $path = current_path();
      $path_alias = drupal_lookup_path('alias',$path);
      $studium = str_replace('studium/', '', $path_alias);
      $html = <<<EOM
<p><img src="/img/$studium-stor.jpg" width="100%" /></p>
EOM;
      return array('#markup' => $html);
    default:
      $name = str_replace('study_small_logo_', '', $which_block);
      if ($name == 'samfunn') {
        $name = 'juss-og-samfunnsfag';
      }
      else if ($name == 'euv') {
        $name = 'videre-og-etterutdanning';
      }
      if ($name == 'ALL') {
        $path = 'emner';
        $img = '/img/alle-emner.jpg';
      } 
      else {
        $img = '/img/' . $name . '.png';
        $path = 'studium/' . $name;
      }
      // if ($name == 'ALL') {
      if (false) {
        $html = <<<EOM
<div style="position: relative;">
<div style="position: absolute; top: 20px; left: 20px;">
<a class="study-small-logo" href="$path" style="color: white;">$title</a>
</div>
<p><a href="$path"><img class="study-small-logo" src="$img" alt=""/></a></p>
</div>
EOM;
      }
      else {
        $html = <<<EOM
<p class="study-small-logo">
<a href="$path"><img class="study-small-logo" alt="" src="$img"></a> 
<a class="study-small-logo" href="$path">$title</a>
</p>
EOM;
      }
      return array('#markup' => $html);
  }
}

/**
 * Implements hook_block_view_MODULE_DELTA_alter().
 *
 * Turning the aggregator block title into a link.
 */
function himoldex_block_view_aggregator_feed_1_alter(&$data, $block) {
  $data['subject'] = '<a href="http://panorama.himolde.no/" title="Nyheter fra Panorama - Høgskolen i Moldes uavhengige nettavis">' . $data['subject']. '</a>'; 
}

function _himoldex_youtube_js($video_id) {
  $html = <<<EOM
<script type="text/javascript">// <![CDATA[
  var tag = document.createElement('script');
  tag.src = "http://www.youtube.com/player_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
  var player;
  function onYouTubePlayerAPIReady() {
    player = new YT.Player('yt_player', {
      playerVars: { 'autoplay': 1, 'autohide': 1, 'rel': 0, 'showinfo': 0},
      height: '100%',
      width: '100%',
      videoId: '$video_id',
      events: {
        'onReady': onPlayerReady}
    });
  }
  function onPlayerReady(event) {
    event.target.mute();
  }
// ]]></script>
EOM;
  return $html;
}
