<?php

/**
 * Implements hook_node_prepare().
 *
 * - Add new videos from YouTube playlist or Mediasite folder for research groups.
 */
function himolder_node_prepare($node) {
  if (!empty($node->nid) && ($node->type == 'research_group')) {
    _himoldex_add_videos_to_node($node);
  }
}

/**
 * Implements hook_block_info().
 */
function himolder_block_info() {
  $blocks['about_social_himolder'] = array(
    'info' => t('HimoldeR: Lenker til Om-siden og sosiale tjenester'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['banner_small_himolder'] = array(
    'info' => t('HimoldeR: Banner liten'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['banner_himolder'] = array(
    'info' => t('HimoldeR: Banner'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['area_small_logo_business'] = array(
    'info' => 'HimoldeR: Liten logo for area Business Administration and Social Sciences',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['area_small_logo_health'] = array(
    'info' => 'HimoldeR: Liten logo for area Health Sciences and Social Care',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['area_small_logo_logistics'] = array(
    'info' => 'HimoldeR: Liten logo for area Logistics',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['area_small_logo_moreforsking'] = array(
    'info' => 'HimoldeR: Liten logo for area Møreforsking Molde',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function himolder_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.
  $block['subject'] = '<none>';
  switch ($delta) {
    case 'about_social_himolder':
    case 'banner_himolder':
    case 'banner_small_himolder':
      $block['content'] = _himolder_block_contents($delta);
      break;
    case 'area_small_logo_business':
      $block['content'] = _himolder_block_contents($delta, 'Business Administration and Social Sciences');
      break;
    case 'area_small_logo_health':
      $block['content'] = _himolder_block_contents($delta, 'Health Sciences and Social Care');
      break;
    case 'area_small_logo_logistics':
      $block['content'] = _himolder_block_contents($delta, 'Logistics');
      break;
    case 'area_small_logo_moreforsking':
      $block['content'] = _himolder_block_contents($delta, 'Møreforsking Molde');
      break;
  }
  return $block;
}

/**
 * Produces the actual block content.
 */
function _himolder_block_contents($which_block, $title='') {
    switch ($which_block) {
    case 'about_social_himolder':
      $html = <<<EOM
<div id="about-social" class="clearfix">
<div class="grid-5">
<!-- a href="/side/om-himoldex">About HiMoldeR</a -->
General: <a href="mailto:post@himolde.no">post@himolde.no</a> / 712&nbsp;14&nbsp;000
</div>
<div class="grid-2 no-margin center">Follow us on
<span class="no-br">
<a href="http://www.facebook.com/himolde" target="_blank"><img src="/img/fb.png"></a>
<a href="http://twitter.com/himolde" target="_blank"><img src="/img/twitter.png"></a>
<a href="http://www.youtube.com/user/himoldex" target="_blank"><img src="/img/youtube.png"></a>
</span>
</div>
<div class="grid-5 last">
Technical: <a href="mailto:support@himolde.no">support@himolde.no</a> / 712&nbsp;14&nbsp;175
</div>
</div>
EOM;
      return array('#markup' => $html);
    case 'banner_small_himolder':
      $html = <<<EOM
<p>
<a href="/"><img src="/img/banner-himolder-liten-2016-01-19.jpg" width="100%" 
title="HiMoldeR.no is an open research platform for Molde University College. 
On this page you'll find our research groups."/></a>
</p>
EOM;
      return array('#markup' => $html);
    case 'banner_himolder':
      $html = <<<EOM
<p>
<a href="/"><img src="/img/banner-himolder-2016-01-19.jpg" width="100%" 
title="HiMoldeR.no is an open research platform for Molde University College. 
On this page you'll find our research groups."/></a>
</p>
EOM;
      return array('#markup' => $html);
    default:
      $name = str_replace(array(' ',','), array('-',''), strtolower($title));
      $name = str_replace('ø', 'o', $name);
      $img = '/img/r/' . $name . '.png';
      $path = '/page/' . $name;

      if (false) {
        $html = <<<EOM
<div style="position: relative;">
<div style="position: absolute; top: 20px; left: 20px;">
<a class="study-small-logo" href="$path" style="color: white;">$title</a>
</div>
<p><a href="$path"><img class="study-small-logo" src="$img" alt=""/></a></p>
</div>
EOM;
      }
      else {
        $html = <<<EOM
<p class="study-small-logo group-small-logo">
<a href="$path"><img class="study-small-logo" alt="" src="$img"></a> 
<a class="study-small-logo group-small-logo" href="$path">$title</a>
</p>
EOM;
      }
      return array('#markup' => $html);
  }
}

/**
 * Implements hook_block_view_MODULE_DELTA_alter().
 *
 * Removing Norwegian "intro" from the items.
 */
function himolder_block_view_aggregator_feed_2_alter(&$data, $block) {
  $data['content'] = str_replace('Ny artikkel - ', '', $data['content']);
}
